# Dependencies
# markdown:         redcarpet
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lyndon Codes
tagline:          'Lyndon Armitage\s Coding Blog'
description:      'Small blog containing code related posts by Lyndon Armitage'
url:              https://lyndon.codes

author:
  name:           'Lyndon Armitage'
  url:            https://twitter.com/LyndonArmitage
  twitter:        https://twitter.com/LyndonArmitage
  github:         https://github.com/LyndonArmitage
  linkedin:       https://www.linkedin.com/in/lyndonarmitage

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lyndonarmitage/lyndonarmitage.github.io
